version: "3.7"

services:

    app:
        build: 
            context: ./App
            dockerfile: Dockerfile
        command: gunicorn mainApp.run:app --bind 0.0.0.0:8080
        container_name: app
        restart: always
        environment: 
            - APP_NAME=CordLte
        expose: 
            - 8080
    nginx:
        build: ./Nginx
        container_name: nginx
        restart: always
        ports:
            - '80:80'
        depends_on:
            - app
