version: "3.7"

services:

    app:
        build: ./App
        command: gunicorn --bind 0.0.0.0:8080 /App/mainApp/run:app
        container_name: app
        restart: always
        environment: 
            - APP_NAME=CordLte
        expose: 
            - 8080
    nginx:
        build: ./Nginx
        container_name: nginx
        restart: always
        ports:
            - 8080:80
        depends_on:
            - app
