version: "3.7"

services:

    app:
        build: ./App
        command: command: gunicorn --bind http://cordlte.com:8080 run:app
        container_name: app
        restart: always
        environment: 
            - APP_NAME=CordLte
        expose: 
            - 8080
    nginx:
        build: ./Nginx
        container_name: nginx
        restart: always
        ports:
            - 8080:80
        depends_on:
            - app
